#buildin--
FROM node:22 AS builder
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@11.5.1 --activate
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm --filter api prisma generate
RUN pnpm --filter api build


# runtym--
FROM node:22-slim
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@11.5.1 --activate
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app .
EXPOSE 5000
CMD ["sh", "-c", "cd apps/api && pnpm prisma migrate deploy && pnpm start"]