name: Web CI

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

  pull_request:
    paths:
      - "apps/web/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack
        run: corepack enable
      
      - name: Prepare pnpm
        run: corepack prepare pnpm@11.5.1 --activate
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Web build
        run: pnpm --filter web build
      
      - name: web test run
        run: pnpm --filter web test